### ISSUE TITLE
Error message for insufficient seed length is strange

### ISSUE THREAD

**Issue by destagia** [isarq/nem-sdk-go#2]
I try to create KeyPair by `mmodel.KeyPairCreate`, but got error.

The error message is following.

```
$ go run main.go
panic: insufficient seed length, should be 32, but got 32
```

I'm not native English speaker, but thought this is strange because it is seems to fulfill the condition. How do you think?

In addition to the above, this package uses many `panic`s . `panic` can't be caught in Go unlike exception the other major languages have, so they should return `error` instead of causing `panic`. This package is in development, then please switch them if you like this thought.

Anyway, thank you for great Go package of NEM!

**Comment by slackve** [comment]
Thank you for your comments! indeed it has some panic, it would be good if you indicate in which part of the functions you would like to catch the error and I will gladly place it!

**Comment by slackve** [comment]
Fixed the error message KeyPairCreate
https://github.com/isarq/nem-sdk-go/commit/cf4a41b5c25f84225ad251ddaf639d9c086fb522

**Comment by destagia** [comment]
@slackve 

Thank you for your quick fixing!

> it would be good if you indicate in which part of the functions you would like to catch the error and I will gladly place it!

OK I'll let you know that as another issue when I notice!
