### ISSUE TITLE
If BlockHeight should use int64

### ISSUE THREAD

**Issue by crossle** [isarq/nem-sdk-go#4]
```
type BlockHeight struct {
	Height int
}
```

The height should is int64?

**Comment by slackve** [comment]
Thank you very much friend for your observation, it was corrected!
https://github.com/isarq/nem-sdk-go/commit/5d7b97ecbe76b3c6cb20e05d893132003767cacc#diff-e762c4bd5dd4653e903c2dfcf4664adb

**Comment by crossle** [comment]
Cool, 👍

**Comment by crossle** [comment]
Why the commit time is  29 Aug 2016 ? 😂

**Comment by slackve** [comment]
I had the username and the bad date on my PC when I made the commit and I realized when it was too late! jijijiji
