### ISSUE TITLE
API sugguestion

### ISSUE THREAD

**Issue by crossle** [isarq/nem-sdk-go#5]
`func NewClient(node Node) Client `
->
`func NewClient(node Node) *Client `

**Comment by slackve** [comment]
Resolved! Thank you very much!
https://github.com/isarq/nem-sdk-go/commit/d52114eeccbbe9d05d9d2c17a2b7160c0e45178c#diff-e762c4bd5dd4653e903c2dfcf4664adb

**Comment by crossle** [comment]
How about this?
```
func NewClient(node Node) *Client {
	host := utils.FormatEndpoint(node)
	host = strings.Replace(host, "http://", "", -1)
	return &Client{Node: node, URL: url.URL{Scheme: "http", Host: host}}
}
```

**Comment by crossle** [comment]
How about add `/local/chain/blocks-after` this API? or expose some like `buildReq`?

**Comment by slackve** [comment]
Would you like to collaborate with this project?

**Comment by slackve** [comment]
&Client It is the simple mode but of equal operation! I like it!

**Comment by crossle** [comment]
> Would you like to collaborate with this project?

OK

**Comment by crossle** [comment]
@slackve  How about  	Transactions  []interface{} `json:"transactions"` use  TransactionResponce struct?

**Comment by crossle** [comment]
https://github.com/isarq/nem-sdk-go/pull/6
@slackve

**Comment by crossle** [comment]
Any process?

**Comment by slackve** [comment]
Greetings friend! create a new branch and let's work the changes there!

**Comment by crossle** [comment]
I ready commit a pull request, review plz

**Comment by slackve** [comment]
Good morning friend! create a branch of development and upload the code!

**Comment by crossle** [comment]
ERROR: Permission to isarq/nem-sdk-go.git denied to

**Comment by slackve** [comment]
Sorry friend, give me a few minutes and I'll let you know, I'm on the street!

**Comment by crossle** [comment]
@slackve  two days passed

**Comment by destagia** [comment]
He must be still on the street

**Comment by crossle** [comment]
> He must be still on the street

😂

**Comment by slackve** [comment]
Hehehe! I was sick in bed!
